/**
* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
* 
* Copyright (c) 2012 - SCAPI (http://crypto.biu.ac.il/scapi)
* This file is part of the SCAPI project.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
* and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
* FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
* WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
* 
* We request that any publication and/or code referring to and/or based on SCAPI contain an appropriate citation to SCAPI, including a reference to
* http://crypto.biu.ac.il/SCAPI.
* 
* SCAPI uses Crypto++, Miracl, NTL and Bouncy Castle. Please see these projects for any further licensing issues.
* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
* 
*/
package edu.biu.scapi.circuits.garbledCircuit;

import java.nio.ByteBuffer;
import java.security.SecureRandom;
import java.util.Map;

import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;

import edu.biu.scapi.circuits.circuit.Gate;
import edu.biu.scapi.circuits.encryption.MultiKeyEncryptionScheme;
import edu.biu.scapi.primitives.kdf.KeyDerivationFunction;
import edu.biu.scapi.primitives.prg.PseudorandomGenerator;

/**
 * The {StandardRowReductionGarbledBooleanCircuit} class is a utility class that computes the functionalities regarding Garbled Boolean Circuit 
 * using the row reduction technique.
 * 
 * @author Cryptography and Computer Security Research Group Department of Computer Science Bar-Ilan University (Moriya Farbstein)
 *
 */
class StandardRowReductionGarbledBooleanCircuitUtil extends StandardGarbledBooleanCircuitUtil {
	
	protected KeyDerivationFunction kdf;
	
	/**
	 * Sets the given MultiKeyEncryptionScheme, kdf and random.
	 * @param mes
	 * @param kdf
	 * @param random
	 */
	StandardRowReductionGarbledBooleanCircuitUtil(MultiKeyEncryptionScheme mes, KeyDerivationFunction kdf, SecureRandom random) {
		super(mes, random);
		this.kdf = kdf;	
		
		
	}
	
	/**
	 * Default constructor.
	 */
	StandardRowReductionGarbledBooleanCircuitUtil(){
		super();
	}
	
	/**
	 * Creates a RowReductionGarbledGate.
	 * @param ungarbledGate to garble.
	 * @param garbledTablesHolder
	 * @return the created gate.
	 */
	protected GarbledGate createGate(Gate ungarbledGate, BasicGarbledTablesHolder garbledTablesHolder) {
		return new StandardRowReductionGarbledGate(ungarbledGate, mes, kdf, garbledTablesHolder);
	}
	
	/**
	 * Creates a RowReductionGarbledGate and fills its garbled table.
	 */
	protected void generateOutputKeys(Map<Integer, SecretKey[]> allOutputWireValues, Gate ungarbledGate, Map<Integer, SecretKey[]> allWireValues) {
		//Sample the value to the key that is not generated by the row reduction technique.
		byte[] otherBytes = mes.generateKey().getEncoded();
		
		//Call the function that calculate the output key according to the row reduction technique.
		generateRowReductionOutputKeys(allWireValues, ungarbledGate, otherBytes);
		
	}
	

	@Override
	protected void generateOutputKeysFromSeed(PseudorandomGenerator prg,Map<Integer, SecretKey[]> allWireValues, Gate ungarbledGate) {
		//Sample the value to the key that is not generated by the row reduction technique.
		byte[] otherBytes = new byte[mes.getCipherSize()];
		prg.getPRGBytes(otherBytes, 0, mes.getCipherSize());
		
		//Call the function that calculate the output key according to the row reduction technique.
		generateRowReductionOutputKeys(allWireValues, ungarbledGate, otherBytes);
		
	}

	/**
	 * Samples keys to the output wires with the row reduction technique.
	 * @param allWireValues A map that contains both keys for each wire.
	 * @param ungarbledGate The gate we want to sample keys for its output wires.
	 * @param otherBytes The value to the key that is not generated by the row reduction technique.
	 */ 
	private void generateRowReductionOutputKeys(Map<Integer, SecretKey[]> allWireValues, Gate ungarbledGate, byte[] otherBytes) {
		int[] indices = ungarbledGate.getInputWireIndices();
		int numberOfInputs = indices.length;
		
		//The number of rows is 2^numberOfInputs - 1. The last row will be calculated by the row reduction technique.
		int numberOfRows = (int) Math.pow(2, numberOfInputs)-1;
		
		//Find the line that we do not save in the table and we use the KDF to find the value of the output key.
		for (int rowOfTruthTable = 0; (rowOfTruthTable <= numberOfRows) && !(allWireValues.containsKey(ungarbledGate.getOutputWireIndices()[0])); rowOfTruthTable++) {
		  	int permutedPosition = 0;
		  	for (int i = 0, j = (int) Math.pow(2, numberOfInputs - 1), reverseIndex = numberOfInputs - 1; i < numberOfInputs; i++, j /= 2, reverseIndex--) {
		  	
		  		/* Truth table inputs are arranged according to binary number values. j is the value that begins as a 1 in the
			   	 * leftmost(most significant bit) of the binary number that is the size of the truth table. Say for example that there are
			   	 * 3 inputs. So the truth table has 3 input columns. j begins as the binary number 100 and we use it to check whether the leftmost bit in
			   	 * the row of the truth table is set. If it is, that means that the input value is a 1.  Otherwise it's a 0. We then divide j by 2 to obtain the binary
			   	 * number 010 and we use this to determine the value of the inputs in the second column. We then divide by 2 again to obtain the 
			   	 * binary number 001 and use it to determine the value of the inputs in the third column.
			   	 */
		  		int input = (((rowOfTruthTable & j) == 0) ? 0 : 1);
		  		
		  		//signal bit is the last bit of k0.
		  		byte[] k0 = allWireValues.get(indices[i])[0].getEncoded();
		  		byte signalBit =  (byte) (k0[k0.length-1] & 1);
		  		
		  		permutedPosition += (input ^ signalBit) * (Math.pow(2, reverseIndex));
		  		
		  	}
		  	
		  	//This is the row that we do not save in the table but calculate the value via KDF.
		  	if (permutedPosition == numberOfRows){
		  		//Allocate a byte array to hold the bytes for the KDF.
		  		ByteBuffer kdfBytes = ByteBuffer.allocate(mes.getCipherSize()*numberOfInputs +16);
		  		
		  		//The input for the kdf should be the concatenation of input keys, gate number and input keys' signal bits.
		  		SecretKey[] keys = new SecretKey[numberOfInputs];
		  		for (int i=0; i<numberOfInputs; i++){
		  			//Get the index of the input key.
		  			int wireKeyIndex = ((rowOfTruthTable & (numberOfInputs - i)) == 0) ? 0 : 1;
		  			//Put each input key in the kdf array.
		  			keys[i] = allWireValues.get(indices[i])[wireKeyIndex];
		  			kdfBytes.put(keys[i].getEncoded());
		  		}
		  		//Put gate number in the kdf array.
				kdfBytes.putInt(ungarbledGate.getGateNumber());
				//Put each signal bit in the kdf array.
				for (int i=0; i<numberOfInputs; i++){
					kdfBytes.putInt((keys[i].getEncoded()[keys[i].getEncoded().length - 1] & 1) == 0 ? 0 : 1);
				}
				
				//Compute the KDF.
				SecretKey wireValue = kdf.deriveKey(kdfBytes.array(), 0, mes.getCipherSize()*numberOfInputs +16, mes.getCipherSize());
				
				//Now we have both values, calculate the signal bit.
				boolean output = ungarbledGate.getTruthTable().get(rowOfTruthTable);
				byte signalBit = 0;
				SecretKey zeroKey, oneKey;
				if (output == false){
					zeroKey = wireValue;
					signalBit = (byte) (wireValue.getEncoded()[wireValue.getEncoded().length - 1] & 1);
					if (signalBit == 0){
						otherBytes[otherBytes.length-1] |= 1;	
					} else{
						otherBytes[otherBytes.length-1] &= 254;
					}
					oneKey = new SecretKeySpec(otherBytes, "");
				} else {
					oneKey = wireValue;
					signalBit = (byte) (1 - (wireValue.getEncoded()[wireValue.getEncoded().length - 1] & 1));
					if (signalBit == 0){
						otherBytes[otherBytes.length-1] &= 254;
					} else{
						otherBytes[otherBytes.length-1] |= 1;	
					}
					zeroKey = new SecretKeySpec(otherBytes, "");
				}
				allWireValues.put(ungarbledGate.getOutputWireIndices()[0], new SecretKey[] {zeroKey, oneKey});
					
		  	}
		}
	}
}
