/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl */

#ifndef _Included_edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl
#define _Included_edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl
 * Method:    createFpPoint
 * Signature: (J[B[B[Z)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl_createFpPoint
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl
 * Method:    createFpPoint
 * Signature: (J[B[B[Z)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl_createFpPointFromX
  (JNIEnv *, jobject, jlong, jbyteArray, jbooleanArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl
 * Method:    createRandomFpPoint
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl_createRandomFpPoint
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbooleanArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl
 * Method:    checkInfinityFp
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl_checkInfinityFp
  (JNIEnv *, jobject, jlong);
/*
 * Class:     edu_biu_scapi_primitives_dlog_miracl_ECF2mPointMiracl
 * Method:    getXValue
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl_getXValueFpPoint
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_miracl_ECF2mPointMiracl
 * Method:    getYValue
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl_getYValueFpPoint
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl
 * Method:    deletePointFp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_dlog_miracl_ECFpPointMiracl_deletePointFp
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
