/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECF2m */

#ifndef _Included_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECF2m
#define _Included_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECF2m
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECF2m
 * Method:    createCurve
 * Signature: ([B[B[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECF2m_createCurve
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECF2m
 * Method:    initCurve
 * Signature: (JJ[B[B)I
 */
JNIEXPORT jint JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECF2m_initCurve
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
