/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECFp */

#ifndef _Included_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECFp
#define _Included_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECFp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECFp
 * Method:    createCurve
 * Signature: ([B[B[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECFp_createCurve
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECFp
 * Method:    initCurve
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLDlogECFp_initCurve
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);


#ifdef __cplusplus
}
#endif
#endif
