/**
* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
* 
* Copyright (c) 2012 - SCAPI (http://crypto.biu.ac.il/scapi)
* This file is part of the SCAPI project.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
* and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
* FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
* WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
* 
* We request that any publication and/or code referring to and/or based on SCAPI contain an appropriate citation to SCAPI, including a reference to
* http://crypto.biu.ac.il/SCAPI.
* 
* SCAPI uses Crypto++, Miracl, NTL and Bouncy Castle. Please see these projects for any further licensing issues.
* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
* 
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <openssl/ec.h>
/* Header for class edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogECAbs */

#ifndef _Included_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC
#define _Included_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC
 * Method:    createInfinityPoint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC_createInfinityPoint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC
 * Method:    inversePoint
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC_inversePoint
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC
 * Method:    exponentiate
 * Signature: (JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC_exponentiate
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC
 * Method:    multiply
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC_multiply
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC
 * Method:    checkCurveMembership
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC_checkCurveMembership
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC
 * Method:    simultaneousMultiply
 * Signature: (J[J[[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC_simultaneousMultiply
  (JNIEnv *, jobject, jlong, jlongArray, jobjectArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC
 * Method:    validate
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC_validate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC
 * Method:    exponentiateWithPreComputedValues
 * Signature: (JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC_exponentiateWithPreComputedValues
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC
 * Method:    deleteDlog
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLAdapterDlogEC_deleteDlog
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}

class DlogEC {
private:

	EC_GROUP* curveP;
	BN_CTX* ctx;
public:

	DlogEC(EC_GROUP* curveP, BN_CTX* ctx);
	~DlogEC();

	EC_GROUP* getCurve();
	BN_CTX* getCTX();

	EC_POINT* createInfinityPoint();
	EC_POINT* inversePoint(EC_POINT*);
	EC_POINT* exponentiate(EC_POINT* base, BIGNUM* exponent);
	EC_POINT* multiply(EC_POINT* point1, EC_POINT* point2);
	BOOL checkCurveMembership(EC_POINT* point);
	EC_POINT* simultaneousMultiply(const EC_POINT** pointsArr, const BIGNUM** exponentsArr, int size);
	BOOL validate();
	EC_POINT* exponentiateWithPreComputedValues(BIGNUM* exponent);
};


#endif
#endif


