/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL */

#ifndef _Included_edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL
#define _Included_edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL
 * Method:    createPoint
 * Signature: (J[B[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL_createPoint
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL
 * Method:    getX
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL_getX
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL
 * Method:    getY
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL_getY
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL
 * Method:    checkInfinity
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL_checkInfinity
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL
 * Method:    deletePoint
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_ECFpPointOpenSSL_deletePoint
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
