/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash */

#ifndef _Included_edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash
#define _Included_edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash
 * Method:    createHash
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash_createHash
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash
 * Method:    algName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash_algName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash
 * Method:    updateHash
 * Signature: (J[BJ)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash_updateHash
  (JNIEnv *, jobject, jlong, jbyteArray, jlong);

/*
 * Class:     edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash
 * Method:    finalHash
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash_finalHash
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash
 * Method:    getDigestSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash_getDigestSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash
 * Method:    deleteHash
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_hash_openSSL_OpenSSLHash_deleteHash
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
