/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_prf_openSSL_openSSLPRP */

#ifndef _Included_edu_biu_scapi_primitives_prf_openSSL_OpenSSLPRP
#define _Included_edu_biu_scapi_primitives_prf_openSSL_OpenSSLPRP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_prf_openSSL_openSSLPRP
 * Method:    computeBlock
 * Signature: (J[B[BI)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_openSSL_OpenSSLPRP_computeBlock
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     edu_biu_scapi_primitives_prf_openSSL_openSSLPRP
 * Method:    invertBlock
 * Signature: (J[B[BI)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_openSSL_OpenSSLPRP_invertBlock
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     edu_biu_scapi_primitives_prf_openSSL_openSSLPRP
 * Method:    doOptimizedCompute
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_openSSL_OpenSSLPRP_doOptimizedCompute
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     edu_biu_scapi_primitives_prf_openSSL_openSSLPRP
 * Method:    doOptimizedInvert
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_openSSL_OpenSSLPRP_doOptimizedInvert
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     edu_biu_scapi_primitives_prf_openSSL_openSSLPRP
 * Method:    deleteNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_openSSL_OpenSSLPRP_deleteNative
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
