/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_prg_openSSL_OpenSSLRC4 */

#ifndef _Included_edu_biu_scapi_primitives_prg_openSSL_OpenSSLRC4
#define _Included_edu_biu_scapi_primitives_prg_openSSL_OpenSSLRC4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_prg_openSSL_OpenSSLRC4
 * Method:    createRC4
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_prg_openSSL_OpenSSLRC4_createRC4
  (JNIEnv *, jobject);

/*
 * Class:     edu_biu_scapi_primitives_prg_openSSL_OpenSSLRC4
 * Method:    initRC4
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prg_openSSL_OpenSSLRC4_initRC4
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_prg_openSSL_OpenSSLRC4
 * Method:    generateBytes
 * Signature: (JI[BI)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prg_openSSL_OpenSSLRC4_generateBytes
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jint);

/*
 * Class:     edu_biu_scapi_primitives_prg_openSSL_OpenSSLRC4
 * Method:    deleteNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prg_openSSL_OpenSSLRC4_deleteNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
