/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation */

#ifndef _Included_edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation
#define _Included_edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation
 * Method:    initRSAPublicPrivate
 * Signature: ([B[B[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation_initRSAPublicPrivate
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation
 * Method:    initRSAPublicPrivateCrt
 * Signature: ([B[B[B[B[B[B[B[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation_initRSAPublicPrivateCrt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation
 * Method:    initRSAPublic
 * Signature: ([B[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation_initRSAPublic
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation
 * Method:    computeRSA
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation_computeRSA
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation
 * Method:    invertRSA
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation_invertRSA
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation
 * Method:    deleteRSA
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_openSSL_OpenSSLRSAPermutation_deleteRSA
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
