/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs */

#ifndef _Included_edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs
#define _Included_edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs
 * Method:    createEncryption
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs_createEncryption
  (JNIEnv *, jobject);

/*
 * Class:     edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs
 * Method:    createDecryption
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs_createDecryption
  (JNIEnv *, jobject);

/*
 * Class:     edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs
 * Method:    getBlockSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs_getIVSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs
 * Method:    encrypt
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs_encrypt
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs
 * Method:    decrypt
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs_decrypt
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs
 * Method:    deleteNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLEncWithIVAbs_deleteNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLCBCEncRandomIV
 * Method:    setKey
 * Signature: (JJLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLCBCEncRandomIV_setKey
  (JNIEnv *, jobject, jlong, jlong, jstring, jbyteArray);

/*
 * Class:     edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLCTREncRandomIV
 * Method:    setKey
 * Signature: (JJLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_midLayer_symmetricCrypto_encryption_OpenSSLCTREncRandomIV_setKey
  (JNIEnv *, jobject, jlong, jlong, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
