/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <openssl/des.h>
/* Header for class edu_biu_scapi_primitives_prf_openSSL_OpenSSLTripleDES */

#ifndef _Included_edu_biu_scapi_primitives_prf_openSSL_OpenSSLTripleDES
#define _Included_edu_biu_scapi_primitives_prf_openSSL_OpenSSLTripleDES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_prf_openSSL_OpenSSLTripleDES
 * Method:    createTripleDES
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_prf_openSSL_OpenSSLTripleDES_createTripleDESCompute
  (JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_prf_openSSL_OpenSSLTripleDES_createTripleDESInvert
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_openSSL_OpenSSLTripleDES_setKey
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

#ifdef __cplusplus
}

class TripleDES {

private:

	DES_key_schedule ks1, ks2, ks3;
public:

	TripleDES(char* key, int size);
	~TripleDES();

	unsigned char* compute(unsigned char* input);
	unsigned char* invert(unsigned char* input);
};
#endif
#endif
