/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_dlog_openSSL_OpenSSLZpSafePrimeElement */

#ifndef _Included_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLZpSafePrimeElement
#define _Included_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLZpSafePrimeElement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLZpElement
 * Method:    createElement
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLZpSafePrimeElement_createElement
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLZpElement
 * Method:    deleteElement
 * Signature: (J)J
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLZpSafePrimeElement_deleteElement
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_openSSL_OpenSSLZpElement
 * Method:    getElement
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_dlog_openSSL_OpenSSLZpSafePrimeElement_getElement
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
