/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionReceiver */

#ifndef _Included_edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionReceiver
#define _Included_edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionReceiver
 * Method:    initOtReceiver
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionReceiver_initOtReceiver
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionReceiver
 * Method:    runOtAsReceiver
 * Signature: (J[BII[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionReceiver_runOtAsReceiver
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
