/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionSender */

#ifndef _Included_edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionSender
#define _Included_edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionSender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionSender
 * Method:    initOtSender
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionSender_initOtSender
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionSender
 * Method:    runOtAsSender
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_interactiveMidProtocols_ot_otExtensionSemiHonest_OTSemiHonestExtensionSender_runOtAsSender
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
