/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionSender */

#ifndef _Included_edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionSender
#define _Included_edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionSender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionSender
 * Method:    initOtSender
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionSender_initOtSender
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionSender
 * Method:    runOtAsSender
 * Signature: (J[B[B[BIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionSender_runOtAsSender
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray, jint, jint, jstring);

/*
 * Class:     edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionSender
 * Method:    deleteSender
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionSender_deleteSender
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
