/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionReceiver */

#ifndef _Included_edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionReceiver
#define _Included_edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionReceiver
 * Method:    initOtReceiver
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionReceiver_initOtReceiver
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionReceiver
 * Method:    runOtAsReceiver
 * Signature: (J[BII[BLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionReceiver_runOtAsReceiver
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jbyteArray, jstring);

/*
 * Class:     edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionReceiver
 * Method:    deleteReceiver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_interactiveMidProtocols_ot_otBatch_otExtension_OTSemiHonestExtensionReceiver_deleteReceiver
  (JNIEnv *, jobject, jlong);


#ifdef __cplusplus
}
#endif
#endif
