/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES */

#ifndef _Included_edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES
#define _Included_edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES
 * Method:    createAESCompute
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES_createAESCompute
  (JNIEnv *, jobject);

/*
 * Class:     edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES
 * Method:    createAESInvert
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES_createAESInvert
  (JNIEnv *, jobject);

/*
 * Class:     edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES
 * Method:    setNativeKey
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES_setNativeKey
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES
 * Method:    computeBlock
 * Signature: (J[B[BIZ)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES_computeBlock
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint, jboolean);

/*
 * Class:     edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES
 * Method:    optimizedCompute
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES_optimizedCompute
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES_getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES
 * Method:    getBlockSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_biu_scapi_primitives_prf_cryptopp_CryptoPpAES_getBlockSize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
