/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_dlog_cryptopp_ZpElementCryptoPp */

#ifndef _Included_edu_biu_scapi_primitives_dlog_cryptopp_ZpElementSafePrimeCryptoPp
#define _Included_edu_biu_scapi_primitives_dlog_cryptopp_ZpElementSafePrimeCryptoPp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_ZpElementSafePrimeCryptoPp
 * Method:    getPointerToElement
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_ZpSafePrimeElementCryptoPp_getPointerToElement
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_ZpElementCryptoPp
 * Method:    deleteElement
 * Signature: (J)J
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_ZpSafePrimeElementCryptoPp_deleteElement
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_ZpElementCryptoPp
 * Method:    getElement
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_ZpSafePrimeElementCryptoPp_getElement
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
