/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime */

#ifndef _Included_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
#define _Included_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
 * Method:    createDlogZp
 * Signature: ([B[B[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime_createDlogZp
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
 * Method:    createRandomDlogZp
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime_createRandomDlogZp
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
 * Method:    getGenerator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime_getGenerator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
 * Method:    getP
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime_getP
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
 * Method:    getQ
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime_getQ
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
 * Method:    inverseElement
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime_inverseElement
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
 * Method:    exponentiateElement
 * Signature: (JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime_exponentiateElement
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
 * Method:    multiplyElements
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime_multiplyElements
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
 * Method:    deleteDlogZp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime_deleteDlogZp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
 * Method:    validateZpGroup
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime_validateZpGroup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
 * Method:    validateZpGenerator
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime_validateZpGenerator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime
 * Method:    validateZpElement
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZpSafePrime_validateZpElement
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
