/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation */

#ifndef _Included_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation
#define _Included_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation
 * Method:    initRSAWithNED
 * Signature: ([B[B[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation_initRSAPublicPrivate
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation
 * Method:    initRSAWithCrt
 * Signature: ([B[B[B[B[B[B[B[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation_initRSAPublicPrivateCrt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation
 * Method:    initRSAWithNE
 * Signature: ([B[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation_initRSAPublic
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation
 * Method:    initRSAWithNumBitsAndE
 * Signature: (I[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation_initRSARandomly
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation
 * Method:    loadRSAName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation_loadRSAName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation
 * Method:    getRSAModulus
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation_getRSAModulus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation
 * Method:    checkRSAValidity
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation_checkRSAValidity
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation
 * Method:    computeRSA
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation_computeRSA
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation
 * Method:    invertRSA
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation_invertRSA
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation
 * Method:    deleteRSA
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAPermutation_deleteRSA
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
