/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primrtives_trapdoorPermutation_cryptopp_CryptoPPTrapdoorElement */

#ifndef _Included_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpTrapdoorElement
#define _Included_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpTrapdoorElement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpTrapdoorElement
 * Method:    getPointerToElement
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpTrapdoorElement_getPointerToElement
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpTrapdoorElement
 * Method:    getElement
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpTrapdoorElement_getElement
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpTrapdoorElement
 * Method:    deleteElement
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpTrapdoorElement_deleteElement
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAElement
 * Method:    getPointerToRandomRSAElement
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRSAElement_getPointerToRandomRSAElement
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRabinElement
 * Method:    getPointerToRandomRabinElement
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoorPermutation_cryptopp_CryptoPpRabinElement_getPointerToRandomRabinElement
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
