/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_prf_miracl_MiraclAES */

#ifndef _Included_edu_biu_scapi_primitives_prf_miracl_MiraclAES
#define _Included_edu_biu_scapi_primitives_prf_miracl_MiraclAES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_prf_miracl_MiraclAES
 * Method:    createAES
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_prf_miracl_MiraclAES_createAES
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_prf_miracl_MiraclAES
 * Method:    computeBlock
 * Signature: (J[BI[BI)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_miracl_MiraclAES_computeBlock
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     edu_biu_scapi_primitives_prf_miracl_MiraclAES
 * Method:    invertBlock
 * Signature: (J[BI[BI)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_miracl_MiraclAES_invertBlock
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     edu_biu_scapi_primitives_prf_miracl_MiraclAES
 * Method:    optimizedCompute
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_miracl_MiraclAES_optimizedCompute
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_prf_miracl_MiraclAES
 * Method:    optimizedInvert
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_miracl_MiraclAES_optimizedInvert
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_prf_miracl_MiraclAES
 * Method:    deleteAES
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_prf_miracl_MiraclAES_deleteAES
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
